- alias: ZWave Soft Reset
  trigger:
    platform: time
    at: '2:30:00'
  action:
    service: zwave.soft_reset

- alias: Zwave Heal
  trigger:
    platform: time
    at: '2:35:00'
  action:
    service: zwave.heal_network

- action:
  alias: Turn off Lizards light
  initial_state: true
  hide_entity: false
  trigger:
  - event: sunset
    platform: sun
  action:
    service: homeassistant.turn_off
    entity_id: switch.lizard_lights_switch

- alias: Turn on Lizards light
  initial_state: true
  hide_entity: false
  trigger:
  - event: sunrise
    offset: '+1:00:00'
    platform: sun
  action:
    service: homeassistant.turn_on
    entity_id: switch.lizard_lights_switch

- action:
  - alias: ''
    data:
      message: Movement detected at house with no one home
      title: Home Burglar Alarm
    service: notify.notify
  alias: Motion Detected Empty House
  condition:
  - condition: state
    entity_id: group.family
    state: not_home
  id: '1507106489795'
  trigger:
  - above: '0'
    entity_id: sensor.entrance_sensor_burglar
    platform: numeric_state

- action:
  - alias: ''
    data:
      message: Smoke has been detected at home. Check Nest service
      subject: Home Smoke Alarm Triggered
    service: notify.notify
  alias: Smoke Detection
  condition: []
  id: '1507107923967'
  trigger:
  - entity_id: sensor.dining_room_nest_protect_smoke_status
    from: Ok
    platform: state
- action:
  - data:
      message: High levels of CO detected, please check Nest service fro details
      subject: Home CO Levels Detected
    service: notify.notify
  alias: CO Detection
  condition: []
  id: '1507108110696'
  trigger:
  - entity_id: sensor.dining_room_nest_protect_co_status
    from: Ok
    platform: state
