- id: '1'
  alias: Turn off Lizards light
  initial_state: true
  hide_entity: false
  trigger:
  - event: sunset
    platform: sun
  action:
  - service: homeassistant.turn_off
    entity_id: switch.lizard_lights_switch

- id: '2'
  alias: Turn on Lizards light
  initial_state: true
  hide_entity: false
  trigger:
  - event: sunrise
    offset: '+1:00:00'
    platform: sun
  action:
  - service: homeassistant.turn_on
    entity_id: switch.lizard_lights_switch

- id: '3'
  alias: Motion Detected Empty House
  initial_state: true
  hide_entity: false
  trigger:
  - above: '0'
    entity_id: sensor.entrance_sensor_burglar
    platform: numeric_state
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.family
      state: not_home
  action:
  - data:
      message: Movement detected at house with no one home
      title: Home Burglar Alarm
    service: notify.sms

- id: '4'
  alias: CO Detection
  initial_state: true
  hide_entity: false
  trigger:
  - from: Ok
    entity_id: sensor.dining_room_nest_protect_co_status
    platform: state
  - from: Ok
    entity_id: sensor.hallway_nest_protect_co_status
    platform: state
  action:
  - data:
      message: High levels of CO detected, please check Nest service fro details
      subject: Home CO Levels Detected
    service: notify.sms

- id: '5'
  alias: Smoke Detection
  initial_state: true
  hide_entity: false
  trigger:
  - from: Ok
    entity_id: sensor.dining_room_nest_protect_smoke_status
    platform: state
  - from: Ok
    entity_id: sensor.hallway_nest_protect_smoke_status
    platform: state
  action:
  - data:
      message: High levels of smoke detected, please check Nest service fro details
      subject: Home smoke alarm triggered
    service: notify.sms

- id: '6'
  alias: Turn off downstairs light
  initial_state: true
  hide_entity: false
  trigger:
  - at: '21:30'
    platform: time
  action:
  - service: homeassistant.turn_off
    entity_id: switch.downstairs_lights_switch

- id: '7'
  alias: Turn on Downstairs light
  initial_state: true
  hide_entity: false
  trigger:
  - event: sunset
    platform: sun
  action:
  - service: homeassistant.turn_on
    entity_id: switch.downstairs_lights_switch



