  - alias: ZWave Soft Reset
    trigger:
      platform: time
      at: '2:30:00'
    action:
      service: zwave.soft_reset

  - alias: Zwave Heal
    trigger:
      platform: time
      at: '2:35:00'
    action:
      service: zwave.heal_network

  - alias: Turn off Lizards light
    initial_state: true
    hide_entity: false
    trigger:
      platform: sun
      event: sunset
    action:
      service: homeassistant.turn_off
      entity_id: switch.lizard_lights_switch

  - alias: Turn on Lizards light
    initial_state: true
    hide_entity: false
    trigger:
      platform: sun
      event: sunrise
      offset: "+01:00:00"
    action:
      service: homeassistant.turn_on
      entity_id: switch.lizard_lights_switch

