homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Sydney

 # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Added to enable video support
ffmpeg:

http:
  api_password: !secret api_password
  # base_url: home-control.home.local:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

camera:
  - platform: synology
    url: !secret camera_url
    username: !secret camera_username
    password: !secret camera_password
    verify_ssl: false

device_tracker:
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false 

ifttt:
  key: !secret ifttt_key

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 10000
  device_config:
    light.study_light_level:
      polling_intensity: 1
    switch.study_light:
      polling_intensity: 1

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

media_player:
# Lounge TV
  - platform: braviatv
    host: 192.168.0.88
    name: Lounge TV
# Music Players
  - platform: squeezebox
    host: 192.168.0.10
    port: 9009
# Lounge Kodi Player
  - platform: kodi
    host: 192.168.0.149
    name: Kodi Lounge
# Stereo AVR
  - platform: denonavr
    host: 192.168.0.148
    name: Lounge AVR
    show_all_sources: False
#    zones:
#      - zone: Zone2
#        name: Deck AVR

apple_tv:
  - host: 192.168.0.144
    name: AppleTV Downstairs
    login_id: 00000000-0c75-dfed-fb9b-e59f62334a07
    credentials: 895712EFD67E2189:C72DD13DF77B99021EC372BABE
  - host: 192.168.0.140
    name: AppleTV Lounge
    login_id: 00000000-0c75-dfed-fb9b-e59f62334a07
    credentials: 4484CBB08AEB74A0:D70159FA6FADA0DE20049CD90D

remote:
  - platform: harmony
    name: Lounge
    host: 192.168.0.156
    activity: Watch Smart TV
  - platform: harmony
    name: Downstairs
    host: 192.168.0.131
    activity: Watch Apple TV 


# Text to speech
tts:
  platform: google

# Notify details
notify: !include notify.yaml

# Switch details
switch: !include switch.yaml

# Group structure file
group: !include groups.yaml

# Automations
automation: !include automations.yaml

# Merged directory for sensors
sensor: !include_dir_merge_list sensor

# Scripts
script: !include scripts.yaml

